### ISSUE TITLE
'Github Page' --> 'GitHub repository'

### ISSUE THREAD

**Issue by mroswell** [nytimes/library#101]
### Context (Environment)
Visit https://nyt-library-demo.herokuapp.com/

### Expected Behavior
- 'GitHub' should be spelled with a capital 'H' in the footer and on document pages
- 'page' should be lowercase in the footer. Or better yet, that should read: "repository"

### Actual Behavior
- GitHub is spelled 'Github' in the footer, and at the top of the Feb 2020 update.
- Github 'Page' is capitalized in the footer. Refers to Page rather than repository.

### To Reproduce
- View footer on any page of 
https://nyt-library-demo.herokuapp.com/ 
and 
- View link near the top of
https://nyt-library-demo.herokuapp.com/the-library-team/community-updates/community-update-february-2020

### Additional Information

(Might be helpful to have a separate Issue type for typos or content suggestions.)

**Comment by mroswell** [comment]
Also, remove extra space and comma in "has confused newcomers, ,"
https://nyt-library-demo.herokuapp.com/the-library-team/community-updates/community-update-february-2020

**Comment by afischer** [comment]
Thanks for opening the issue! Since those pages are archives of emails sent out, it seems best not to edit them after they've been sent (even if that means leaving in some of my typos 😬 ). Regarding the other string changes, I'll make some updates and they should go out next time we deploy the public site.
