### ISSUE TITLE
custom/userAuth can't have .js extension

### ISSUE THREAD

**Issue by tarekrached** [nytimes/library#201]
### Context (Environment)
Node `12.18.3` on linux

### Expected Behavior
Be able to override `server/userAuth.js` with `custom/userAuth.js`

### Actual Behavior
If we have `custom/userAuth.js`, the following debug statement shows up:
```
debug: No custom file "userAuth" found in /stitchfix/portal/custom/userAuth. Did you mean to include one?
```

If we have `custom/userAuth` (without the `.js` extension), the override works as expected.

**Comment by isaacwhite** [comment]
Hey @tarekrached, thanks for passing this along. 

I think you are onto something here: that debug statement is incorrect, because it is not looking for a file with the extension, as you mention. However, we do use this pattern successfully with our [demo site](https://nyt-library-demo.herokuapp.com/) with the file located in `custom/userAuth.js`, so I wonder if something else could be going on here, too.

Could it be that something about the userAuth file is throwing a syntax error when the js extension is added? We should do a better job logging this in the import of custom files; when I did this locally I got the same error as you mention above even though the file definitely exists.

**Comment by tarekrached** [comment]
I don't _think_ any errors are getting thrown - our `custom/userAuth` is pretty straightforward.

I tried renaming `custom/userAuth` to  `custom/userAuth.js` to see if the latter was being touched, and of course now it's working again.  Closing bc I can't repro my own bug, I guess?
