### ISSUE TITLE
incorrect logged in user in nav bar

### ISSUE THREAD

**Issue by JoeGermuska** [nytimes/library#30]
### Context (Environment)
Knight Lab's installation of Library

### Expected Behavior
To see my name/email in the top right corner of the navbar when I am logged in. I know that I am logged in because I can see the "edit page" link on pages, and when I click on them, they open, and I can, in fact, edit them.

### Actual Behavior

![image](https://user-images.githubusercontent.com/46313/58584017-eb4d8f00-821a-11e9-952c-0b28ab126671.png)

### To Reproduce
I don't have access to another installation of Library to find out if this common. 

### Additional Information

Knight Lab's Library uses Google Drive folder, not Team Drive

I have multiple Google identities active in this browser; generally, my `gmail` identity is the default, but for Library, my `u.northwestern.edu` (GSuite for Education) account is required.  

### Possible Solution
Maybe the folder, instead of Team Drive, results in confusion over my current identity?

Maybe the fact that I have multiple active Google logins in this session causes confusion with the identity?

cc @maxine

**Comment by isaacwhite** [comment]
Hey @JoeGermuska, the demo username is set as part of a middleware provided in the customization example repo. It's included there because we use that repo to run the [demo site](http://nyt-library-demo.herokuapp.com). See: https://github.com/nytimes/library-customization-example/blob/master/userAuth.js

It sounds like you are running a fork of the customization repo, so you should remove that override userAuth file from your copy and the normal authentication layer should kick in.
