### ISSUE TITLE
Support for iframe videos

### ISSUE THREAD

**Issue by thomasoide** [nytimes/library#67]
### Problem Description
Library blocks video embed codes from rendering on the page, even when using the custom power user markup feature. 

### Additional Information

Here's a screenshot of the error in production:

![Screen Shot 2019-10-15 at 3 23 30 PM](https://user-images.githubusercontent.com/30636067/66868108-5695c480-ef62-11e9-8319-9712f08955e0.png)

Here's a screenshot of the Google Doc:

![Screen Shot 2019-10-15 at 3 25 13 PM](https://user-images.githubusercontent.com/30636067/66868245-99579c80-ef62-11e9-82e1-3d8c531c4ad3.png)

**Comment by afischer** [comment]
Looks like our [content security policy](https://github.com/nytimes/library/blob/master/server/csp.json) is the issue here 
> `Refused to frame 'https://www.youtube.com/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.` 

You should be able to override this by allowing youtube in a `frameSrc` directive. Under the hood, we're using `helmet-csp` which supports [many more directives](https://github.com/helmetjs/csp#supported-directives) than we have explicitly set in csp.json. 

This probably warrants a larger discussion about our default policy and what should be allowed by default, though.

**Comment by afischer** [comment]
Just spoke with @shawn620 and we identified some next steps:

1. Update `csp.json` to include a `frameSrc` directive that contains *.youtube.com as a start
2. Add a new function to `formatter.js` that (for now) identifies *.youtube.com/watch?v=XXX links and transforms them into iframes with the format
```html
<iframe src="*.youtube.com/watch?v=XXX" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

For now, we will convert all youtube links into for iframes, but after this work is done, we will talk about if we want to create some type of special syntax for embeds.
